name: Frontend service

on:
  push:
    branches: 
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3

    - name: Build Frontend
      run: |
        npm install
        npm ci
        npm run build -if-present