name: Matching service

on:
  push:
    paths: [ "matching-service/**" ]
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./matching-service

    steps:
    - uses: actions/checkout@v3

    - name: Build matching service
      run: |
        npm install
        npm ci
        npm run build -if-present
