name: User service

on:
  push:
    paths: [ "/user-service/**" ]
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./user-service/

    steps:
    - uses: actions/checkout@v3

    - name: Build user service
      run: |
        npm install
        npm ci
        npm run build -if-present
